### ISSUE TITLE
how to deploy the model on my own robot car

### ISSUE THREAD

**Issue by wmh02240** [natesimon/MonoNav#2]
Hello, I see this paper [NoMaD: Goal Masking Diffusion Policies for Navigation and Exploration](https://general-navigation-models.github.io/nomad/index.html) quoted in your paper, I deployed this model (NoMad) in my own robot car, but the obstacle avoidance effect is not obvious, I do not know how to solve the problem, Can you give me some advice？
Looking forward to your reply，Thank you！
ps：this picture is the robot car。
![pic](https://github.com/natesimon/MonoNav/assets/42089945/0d43f5b4-bb49-4235-bfec-0304839b2140)

**Comment by natesimon** [comment]
Hi @wmh02240 , since this issue pertains only to [visualnav-transformer](https://github.com/robodhruv/visualnav-transformer/) repo and not MonoNav, I just [responded to your issue](https://github.com/robodhruv/visualnav-transformer/issues/13) there :-).

**Comment by wmh02240** [comment]
Okay，Thanks for your reply。
