### ISSUE TITLE
Hardware compatibility

### ISSUE THREAD

**Issue by limi0129** [natesimon/MonoNav#4]
Hello! First of all, I'd like to express my appreciation for your project, it's great work!
While browsing your project, I found a small problem, and hope you can help me solve it. I noticed that your experimental tests were conducted on the Ubuntu system. Still, in the introduction of the video receiver you provided, it was mentioned that the hardware is suitable for the Windows system. Are there any specific actions or configurations that would make it go smoothly?
Thank you again for your efforts and contributions. Looking forward to your reply!

**Comment by natesimon** [comment]
Hi @limi0129, thank you for your comment!

As you mentioned, MonoNav is designed to be run on an Ubuntu system.

The [hardware](https://github.com/natesimon/MonoNav?tab=readme-ov-file#mononav-hardware) is based on [Princeton's Introduction to Robotics](https://github.com/Princeton-Introduction-to-Robotics/) course. This course supports the use of Linux, Windows, and Mac systems. So the hardware itself (drone, radio, video receiver) is compatible with either system, though each may require unique setup.

I hope this answers your question!

**Comment by limi0129** [comment]
Well. Thank you for your reply!
